In [1]:
!pip install flask-ngrok
!pip install gevent
!pip install flask
!pip install ngrok

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A S U S\AppData\Local\Temp\pip-install-jqdankr9\ping_f8b65298521f4ee58baa9b2f3c7994db\setup.py", line 23, in <module>
          from ping import __version__
        File "C:\Users\A S U S\AppData\Local\Temp\pip-install-jqdankr9\ping_f8b65298521f4ee58baa9b2f3c7994db\ping.py", line 196
          except socket.error, (errno, msg):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue


  Using cached ngrok-0.1.6.tar.gz (3.5 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached ping-0.2.tar.gz (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


In [2]:
!pip install pyngrok

In [3]:

!ngrok authtoken 2BSOwy2L4FINV7Qc3ZenJdwsrMO_VgMdfj4pD8K1YewwG74v

Authtoken saved to configuration file: C:\Users\A S U S/.ngrok2/ngrok.yml


In [4]:
from __future__ import division, print_function
# coding=utf-8
import sys
import os
import glob
import re
import numpy as np
# Keras
from keras.applications.imagenet_utils import preprocess_input, decode_predictions
from keras.models import load_model
from keras.preprocessing import image
# Flask utils
from flask import Flask, redirect, url_for, request, render_template
from werkzeug.utils import secure_filename
from gevent.pywsgi import WSGIServer

In [5]:
import flask
from flask import request
import pandas as pd
import tensorflow as tf
import keras
import numpy as np
import random
import os
from os.path import join, dirname, realpath
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from flask_ngrok import run_with_ngrok
from werkzeug.utils import secure_filename
import json

In [10]:
app = Flask(__name__)
model = tf.keras.models.load_model('UasWAD.h5')
run_with_ngrok(app)


In [11]:
@app.route('/', methods=['GET'])
def index():
  return "<h1>Hello World</h1>"
@app.route('/predict2', methods=['GET', 'POST'])
def upload():
  data={"success":False}
  namafile=''
  if request.method == 'POST':
    file = request.files['file']
    if file.filename == '':
      data["file"]="Tidak ada file"
    else:
      data["file"]="File berhasil di simpan"
      filename = secure_filename(file.filename)
      file.save('data_tes/'+file.filename)
      namafile='data_tes/'+file.filename
    img = load_img(namafile, target_size=(150, 150))
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    x /= 255.0
    predict_prob=model.predict(x, batch_size=1)
    data["success"]=True
    label=0
    predict_classes=np.argmax(predict_prob,axis=1)#indezx dengan prob tertinggi
    label=(int)(predict_classes[0])
    data["label"]=label
    print(predict_classes[0])
    print(predict_prob)
    out_file = open("data.json","w")
    data=json.dump(data, out_file, indent=6)
    out_file.close()
    return flask.jsonify(data)

In [12]:
app.run()

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)


 * Running on http://a0d8-140-213-147-27.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


127.0.0.1 - - [22/Jul/2022 11:31:39] "POST /predict2 HTTP/1.1" 200 -


1
[[6.1106867e-08 9.9999988e-01 1.7970113e-10]]


127.0.0.1 - - [22/Jul/2022 11:42:22] "POST /predict2 HTTP/1.1" 200 -


2
[[1.8118515e-05 4.3345394e-10 9.9998188e-01]]


127.0.0.1 - - [22/Jul/2022 11:45:56] "POST /predict2 HTTP/1.1" 200 -


1
[[7.4180774e-04 9.9917251e-01 8.5654676e-05]]


127.0.0.1 - - [22/Jul/2022 11:46:33] "POST /predict2 HTTP/1.1" 200 -


2
[[1.8118515e-05 4.3345394e-10 9.9998188e-01]]


127.0.0.1 - - [22/Jul/2022 11:48:09] "POST /predict2 HTTP/1.1" 200 -


2
[[1.8118515e-05 4.3345394e-10 9.9998188e-01]]


127.0.0.1 - - [22/Jul/2022 11:48:23] "POST /predict2 HTTP/1.1" 200 -


1
[[7.4180774e-04 9.9917251e-01 8.5654676e-05]]


127.0.0.1 - - [22/Jul/2022 11:48:52] "POST /predict2 HTTP/1.1" 200 -


2
[[9.1911147e-07 2.8287600e-10 9.9999905e-01]]
